---
apiVersion: v1
kind: Pod
metadata:
  name: caddy-pod
  labels:
    app: caddy
    environment: production
spec:
  containers:
    - name: caddy
      image: docker.io/rahhul1309/static-site:latest
      ports:
        - containerPort: 8080
      env:
        - name: LIVENESS_PATH
          valueFrom:
            configMapKeyRef:
              name: caddy-config
              key: LIVENESS_PATH
      envFrom:
        - configMapRef:
            name: caddy-config
      readinessProbe:
        httpGet:
          path: "/"
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: "/$(LIVENESS_PATH)"
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
  imagePullSecrets:
    - name: caddy-secret
